#!/bin/bash
ARCH=`uname -m`

if [[ $ARCH =~ [0-9]86 ]]; then
  export PATH=$PATH:"$PWD/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin"
else
  export PATH=$PATH:"$PWD/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin"
fi

export SWT_GTK3=0

./eclipse/eclipse -data workspace
